### ISSUE TITLE
Result == Cubic

### ISSUE THREAD

**Issue by zvezdochiot** [rageworx/SRCNN_OpenCV_GCC#2]
https://github.com/rageworx/SRCNN_OpenCV_GCC/blob/46119140b7438d77a620b89ab56b374b83119e0e/src/SRCNN.cpp#L593-L594

to

```c
    Mat pImgYCrCbOut;
    pImg[0] = pImgConv3;
    merge(pImg, pImgYCrCbOut);
```
Not? See https://github.com/shuwang127/SRCNN_Cpp/issues/3

**Comment by rageworx** [comment]
yes. this bug belong to original OpenCV codes.
did you checked my new non-OpenCV codes in here(https://github.com/rageworx/libsrcnn)
It much faster than OpenCV models.

**Comment by rageworx** [comment]
Your fixed code may fetched.

**Comment by zvezdochiot** [comment]
@rageworx say> did you checked my new non-OpenCV codes in here

The same garbage with memory. See https://github.com/ImageProcessing-ElectronicPublications/srcnncv/commit/dbc0b4cff8aa5d78e15ca3869f6c33ce10b5d388

**Comment by rageworx** [comment]
thanks I will update your matrix kernel on libscrnn.
but sorry for this clone repo.

**Comment by rageworx** [comment]
Your codes commited to 'cnn-0' branch and tag.
But your codes may seems to smarter but not good in performance.
Here, some results in performance at i7-7700 + MinGW-W64 + OpenCV4 + OpenMP.

version 0.1.4.6 ( Layer I, II, III sequencely )
![image](https://user-images.githubusercontent.com/6948225/63566732-33294b80-c5a9-11e9-88ac-cf4965072d94.png)

version 0.1.5.21 ( Layer I+II, III sequencely )
![image](https://user-images.githubusercontent.com/6948225/63566780-594eeb80-c5a9-11e9-95ce-d232ab6819e2.png)

Do you have any more faster option ?

**Comment by rageworx** [comment]
Plus, here's performance result at AARCH64.
You can check out here : https://github.com/rageworx/SRCNN_OpenCV_GCC/wiki/Performance-bench-for-CNN-0-branch.

**Comment by zvezdochiot** [comment]
@rageworx say> Do you have any more faster option ?

You did not understand the motives of my commits. All of them are aimed at reducing the use of resources. This is necessary for use on older machines and to increase the acceptable size of the original image. Runtime for me is a secondary indicator.

**Comment by rageworx** [comment]
> You did not understand the motives of my commits. All of them are aimed at reducing the use of resources. This is necessary for use on older machines and to increase the acceptable size of the original image. Runtime for me is a secondary indicator.

zvezdochiot, my clone repo was belong to make it for more faster with OpenMP, yes - it was pointed to performance. Your commits very thankful but my repo was discontinued because there's nothing important issue for performance with OpenCV - you may know OpenCV not so fast, not so good to run old machines - so I converted all codes runs on C++ only to new libsrcnn repo. 
Anyway, your announcements shall help me continue to save memory by calc in once for Convolution99x11().
Any good idea ? let keep in touch.
Regards, Raph.

**Comment by zvezdochiot** [comment]
@ragework say> Any good idea ? let keep in touch.

Ok. 

PS: A good idea is to remove bicubic scaling (work with the original image), rebuild the network from one to four outputs and retrain it. This will reduce the cost of resources by another three times and a more correct result.

**Comment by rageworx** [comment]
> A good idea is to remove bicubic scaling (work with the original image)
I will try with libsrcnn ( it has non-filter option ).

**Comment by zvezdochiot** [comment]
@rageworx say> I will try with libsrcnn ( it has non-filter option ).

Not. This CNN works with a 1: 1 image and is trained to correct bicubic interpolation. I'm talking about CNN, working 1: 4 and trained to scale.

**Comment by rageworx** [comment]
> Not. This CNN works with a 1: 1 image and is trained to correct bicubic interpolation. I'm talking about CNN, working 1: 4 and trained to scale.

Ok.
