### ISSUE TITLE
CNN trained for x2?

### ISSUE THREAD

**Issue by zvezdochiot** [rageworx/SRCNN_OpenCV_GCC#5]
Subj.

The best result is obtained if this CNN is used to double, and the rest of the scaling is done by bicubic interpolation.

CNN x4:  
![CNNx4](https://i106.fastpic.ru/big/2019/0820/a9/6e0e6570b67fb39f838604da34da8ba9.jpg)

CNN x2 + BiCubic x2:
![CNNx2+CUBx2](https://i106.fastpic.ru/big/2019/0820/1d/d2762b99454229298943044312395a1d.jpg)

**Comment by rageworx** [comment]
You may understand my original codes belong to convolution for Y (gray) channel only. CrCb channels are scaling with linear, so result may not clear for best result as you described.

**Comment by rageworx** [comment]
here is result for libscrnn ( non-OpenCV model ) runs as you expected, and more options like lanczos3.
![image](https://user-images.githubusercontent.com/6948225/63420376-7ff21280-c441-11e9-83f9-1381161c8483.png)

**Comment by zvezdochiot** [comment]
@rageworx say> here is result for libscrnn

That's right, x2, as I said.
