### ISSUE TITLE
No CV release.

### ISSUE THREAD

**Issue by zvezdochiot** [rageworx/SRCNN_OpenCV_GCC#7]
Hi @rageworx .

See [stb-image-srcnn](https://github.com/ImageProcessing-ElectronicPublications/stb-image-srcnn). This is your SRCNN implementation in C without OpenCV. Use [stb](https://github.com/nothings/stb.git).

Good luck.

**Comment by rageworx** [comment]
Thanks,

But did you checked my older source code of libsrcnn ?

https://github.com/rageworx/libsrcnn

It doesn't use openCV, and testing source made for FLTK as my favorite GUI
engine.

Regards, Raph.


2023년 1월 4일 (수) 오후 11:09, звездочёт ***@***.***>님이 작성:

**Comment by zvezdochiot** [comment]
@rageworx say:
>But did you checked my older source code of libsrcnn ?

Yes, I checked. And it exactly repeats the original scheme with memory abuse. I reduced all the layers into one function, reducing the memory of CNN consumption to `32*resize_height*resize_width*sizeof(float)` (`== 43*resize_image`). Total memory usage: `source_image+resize_image+CNN=175*source_image=44*resize_image`.

Good Luck.

**Comment by rageworx** [comment]
It was an issue that reported by you, so I made a new branch here,
- https://github.com/rageworx/SRCNN_OpenCV_GCC/tree/cnn-0
Is it a different one ? ( except using OpenCV )
As I remember, there's performance issue except less memory usage with openMP.
I will check what's difference and cosider update libsrcnn instead this legacy project.

Regards, Raph.

_ps_
What meaning of Good Luck ? Something regarding way of your home ? Let me know.

**Comment by rageworx** [comment]
It will take long term by understanding codes again about 4 years ago.

**Comment by rageworx** [comment]
Closing this issue, follow this issue : https://github.com/rageworx/libsrcnn/issues/10

**Comment by rageworx** [comment]
Appreciate to @zvezdochiot !
